### ISSUE TITLE
Publish first alpha pkg - 0.0.1

### ISSUE THREAD

**Issue by castarco** [LyraSearch/plugin-astro#1]
Just that, we should publish the package to the NPM registry.

**Comment by micheleriva** [comment]
@castarco is that ready for publishing?

**Comment by castarco** [comment]
Not yet, I want to push another PR that I'm working on before that.

**Comment by castarco** [comment]
@micheleriva Now it is. :) .

It's still a toy with a lot of stuff to be improved, but it will be useful to have that package in the registry, as the minimal feature set is already there.
