### ISSUE TITLE
ignore case when doing route and path matching

### ISSUE THREAD

**Issue by david10sing** [LyraSearch/plugin-astro#28]
I am working on an astro internal site and wanted to get Lyra a go for indexing the content of the site.

We have the following folder structure

```
docs
-> components
--> MyComponent
----> index.md
```

The path matcher was not working because the path matching is case sensitive.

https://github.com/LyraSearch/plugin-astro/blob/4f209680cf7df957b65618e20c95487ffe64c71c/src/index.ts#L65

**Possible solution**
```
r.route.replace(/(^\/|\/$)/g, '').toLowerCase() === pathname.replace(/(^\/|\/$)/g, '').toLowerCase()
```

Let me know if I can create a pull request.

Cheers

**Comment by castarco** [comment]
Hi @david10sing , I think it makes sense to keep the case sensitivity for the general case, but I would be open for a PR where we add an option to change this behavior.

**Comment by david10sing** [comment]
@castarco 

I can add a `caseSensitive` boolean to the `dbConfig`. Could I get permission to push please?

**Comment by castarco** [comment]
It would be best to start by submitting pull requests before granting these permissions to anyone (I'm not sure I have push permissions myself, as I transfered the ownership to the Lyrasearch lrganozarion, but this doesn't pose a problem).

**Comment by david10sing** [comment]
@castarco could I get a review on the above ☝️  please.

Thank you

**Comment by castarco** [comment]
#30 Fixes this.
